### ISSUE TITLE
How to only parse one language?

### ISSUE THREAD

**Issue by ghost** [Natanel-Shitrit/LanguagePhrasesParser#1]
This is just what I needed! However, how could I make it only parse one language? I have no need for other languages, just English. I know I can set the language when translating, but I would prefer to not parse the other languages. Thanks!

**Comment by Natanel-Shitrit** [comment]
Hey, thanks for taking an interest in the project.
I can do something about the languages - probably on the weekend when I'm home.

If you have any cpp knowledge it's fairly easy to modify, just need to alter `phrasesgen.cpp` where it's looping the languages (maybe remove the loop and hardcore the language to `english`.

Maybe I'll do a whitelist for languages but that will happen only when I'm home. (Or if someone will PR it)

**Comment by thrownawaygithub** [comment]
So I see the feature merged and I got the latest release but it doesn't seem to work or maybe I can't get it to work. I manually created the `whitelist.txt` in the config folder that it generated and tried `english` but it still generated the other languages. I also tried leaving it blank and deleting the `whitelist.txt`. Maybe provide an example `whitelist.txt` or is it still WIP? Thanks!

**Comment by Natanel-Shitrit** [comment]
Hey!
I tested it and it worked great, what you tried should work.
You can try to enable `developer 1` in your server console and see the extension output.
(you can do `developer 1` and then unload and load the extension)

**Comment by Natanel-Shitrit** [comment]
```
developer 1
sm exts list
[SM] Displaying 10 extensions:
[01] Automatic Updater (1.11.0.6843): Updates SourceMod gamedata files
[02] Webternet (1.11.0.6843): Extension for interacting with URLs
[03] Language File Parser (1.0): Exposes methods to process game localization files
[04] LanguagePhrasesParser (1.0.0.0):
[05] CS Tools (1.11.0.6843): CS extended functionality
[06] BinTools (1.11.0.6843): Low-level C/C++ Calling API
[07] SDK Tools (1.11.0.6843): Source SDK Tools
[08] Top Menus (1.11.0.6843): Creates sorted nested menus
[09] Client Preferences (1.11.0.6843): Saves client preference settings
[10] SQLite (1.11.0.6843): SQLite Driver
sm exts unload 4
[SM] Extension LanguagePhrasesParser.ext.2.csgo.so is now unloaded.
sm exts load LanguagePhrasesParser
[SM] Loaded extension LanguagePhrasesParser.ext.so successfully.
Processing 'en' "english"
        Parsed 27785
skipping arabic (not in whitelist)
skipping brazilian (not in whitelist)
skipping bulgarian (not in whitelist)
skipping czech (not in whitelist)
skipping danish (not in whitelist)
skipping dutch (not in whitelist)
skipping finnish (not in whitelist)
skipping french (not in whitelist)
skipping german (not in whitelist)
skipping greek (not in whitelist)
skipping hebrew (not in whitelist)
skipping hungarian (not in whitelist)
skipping italian (not in whitelist)
skipping japanese (not in whitelist)
skipping koreana (not in whitelist)
skipping latvian (not in whitelist)
skipping lithuanian (not in whitelist)
skipping norwegian (not in whitelist)
skipping polish (not in whitelist)
skipping portuguese (not in whitelist)
skipping romanian (not in whitelist)
skipping russian (not in whitelist)
skipping schinese (not in whitelist)
skipping slovak (not in whitelist)
skipping spanish (not in whitelist)
skipping swedish (not in whitelist)
skipping tchinese (not in whitelist)
skipping thai (not in whitelist)
skipping turkish (not in whitelist)
skipping ukrainian (not in whitelist)
skipping vietnamese (not in whitelist)
Generated translations in "sourcemod/translations/" (515ms)
```

**Comment by thrownawaygithub** [comment]
Apparently it can't find the whitelist for some reason. Would it be a problem with the folder name? I see in the extension code it is `LanguagePhrasesParser/whitelist.txt` but the folder that is being generated is `languagephrasesparser`.

![image](https://user-images.githubusercontent.com/97135649/148617422-293ee9cd-0471-4280-a17d-c3d0fc2f5328.png)

**Comment by Natanel-Shitrit** [comment]
what's your server OS?
sounds like windows problem with case insensitive filesystem.

**Comment by thrownawaygithub** [comment]
It is Ubuntu Linux, I am remote connecting in VSCode.

**Comment by Natanel-Shitrit** [comment]
I'll do that, thanks for testing!

**Comment by Natanel-Shitrit** [comment]
Forgot to close that, everything is fixed now :)
