### ISSUE TITLE
Token values must be imported case-insensitive

### ISSUE THREAD

**Issue by gaejuck** [Natanel-Shitrit/LanguagePhrasesParser#4]
> Valve's localization system performs a case-insensitive match for localization token lookups, so the behavior of the game and your plugin (or SourceMod's translation system) behaves differently in that way.

Like[ this issue](https://github.com/nosoop/SM-TFEconData/issues/16), we need to be able to import values regardless of case.

**Comment by Natanel-Shitrit** [comment]
Hey, thanks for letting me know, please test the [following build](https://github.com/Natanel-Shitrit/LanguagePhrasesParser/actions/runs/2140814899) and tell me if that's now resolved so I can merge #5 with the main branch!

**Comment by gaejuck** [comment]
It's working properly. Thanks!
If there's one problem, other languages except English are not properly encoded.
However, there is no problem when using it inside the server.
![image](https://user-images.githubusercontent.com/65405568/162581262-68a058d4-cfe6-4ea2-b45e-47a0c1764262.png)

**Comment by Natanel-Shitrit** [comment]
Is the new problem related to this change?
If not - please open another issue, and let me know if I can merge this without bringing new bugs.

**Comment by gaejuck** [comment]
Oh, It's not related to each other. Then I'll open an issue.
