### ISSUE TITLE
Other languages except English are not properly encoded

### ISSUE THREAD

**Issue by gaejuck** [Natanel-Shitrit/LanguagePhrasesParser#6]
As shown in the image, the annotation is encoded normally, but the token value is not.
However, there is no problem when using it inside the server.
![image](https://user-images.githubusercontent.com/65405568/162582196-e85b5a17-c6bd-4095-a59e-29b1d4ae2e87.png)

**Comment by Natanel-Shitrit** [comment]
Could you please attach the file?
I suspect it may be a problem with the encoding of the program you are using.

**Comment by gaejuck** [comment]
[translations.zip](https://github.com/Natanel-Shitrit/LanguagePhrasesParser/files/8457336/translations.zip)

**Comment by Natanel-Shitrit** [comment]
This does look correct to me, please verify 😄
![image](https://user-images.githubusercontent.com/65548905/162582814-0ff1bb14-96b7-4893-a89c-86c36a3d0c0d.png)

**Comment by gaejuck** [comment]
Oh, my God. It must have been my computer encoding problem.
It seems that the file is encoded in EUC-KR instead of UTF-8.

**Comment by Natanel-Shitrit** [comment]
That's alright, I was expecting that because you said everything was fine in-game :)
Thanks for reporting issues you have with this extension, it helps everyone who uses it!
